#7 Contact us page
annay54/culinary-canvas pull request #26
Opened 2024-12-27 04:32 UTC by annay54

- fixed #7 and made it responsive
- changed "class" attribute to "className" attribute in html icon element to resolve error in Navbar and FAQDropDown

2024-12-27 05:23 UTC, anniey54 requested changes

2024-12-27 05:23 UTC, anniey54 commented on src/pages/contact.jsx
> +          )}
instead of using deviceSize, you can just do something like max-w-[1024px]:w-full for line 56 and min-w-[1024px]:flex-row for line 61, etc.

2024-12-27 05:23 UTC, anniey54 commented on src/pages/contact.jsx
> +            </div>
when the screen width is around 1028px, the first and last name fields are squished
![image](https://github.com/user-attachments/assets/073fb082-4a6c-4c27-9398-455e41f8e394)

2024-12-27 05:23 UTC, anniey54 commented on src/pages/contact.jsx
> +          <textarea placeholder="Message" className="p-2 border-2 rounded-md border-secondary text-primary placeholder:text-primary font-normal placeholder:font-normal text-base placeholder:text-base
since you can adjust the textarea height, you should add restriction 
![image](https://github.com/user-attachments/assets/30d8985d-78f1-47fd-96db-dc6030725935)

2024-12-27 05:23 UTC, anniey54 commented on src/components/FAQDropdown.jsx
>                    ></i>
you should make the entire row (containing the icon and question) clickable, so I can click the question to open or close the answer

2024-12-29 21:30 UTC, annay54 commented on src/pages/contact.jsx
> +          )}
implemented the change

2024-12-29 21:37 UTC, annay54 commented on src/pages/contact.jsx
> +          <textarea placeholder="Message" className="p-2 border-2 rounded-md border-secondary text-primary placeholder:text-primary font-normal placeholder:font-normal text-base placeholder:text-base
implemented the change

2024-12-29 21:43 UTC, annay54 commented on src/components/FAQDropdown.jsx
>                    ></i>
implemented change

2024-12-29 21:48 UTC, annay54 commented on src/pages/contact.jsx
> +            </div>
I think it's fine. It's not really squished.

2024-12-29 22:15 UTC, anniey54 approved these changes

2024-12-29 22:15 UTC, merged